[package]
name = "cat_engine"
version = "0.5.0"
authors = ["Clomance <Hisoskar@gmail.com>"]
edition = "2018"
homepage = "https://github.com/Clomance/CatEngine"
repository = "https://github.com/Clomance/CatEngine"
description = "A 2D graphics engine with audio output support"
documentation = "https://docs.rs/cat_engine/"
license = "MIT"
readme = "README.md"
keywords = ["graphics","opengl","audio","playback"]
exclude = [
    "resources",
    "LICENSE",
    ".gitignore",
    "logo_400x400.png",
    "logo.png",
    "examples",
    "book",
    "RELEASE-NOTES.MD"
]

[features]
default = ["text_graphics","simple_graphics","texture_graphics"]

# audio
audio = ["cpal","minimp3"]

# I will add them later
# choose_audio_output_device = []
# choose_audio_output_device_format = []
# choose_audio_output_device_on_error = []
# choose_audio_output_device_format_on_error = []

# text
text_graphics = ["ttf-parser","ab_glyph_rasterizer"]
glyph_cache = []

simple_graphics = []
texture_graphics = []

# window
auto_hide = []
fps_counter = []
lazy = []
file_drop = []

2D = []
3D = []

[package.metadata.docs.rs]
features = [
    "default",
    "audio",
    "auto_hide",
    "fps_counter",
    "file_drop"
]

[dependencies]
# main
image = "0.23.9"
glium = "0.27.0"
# text
ttf-parser = { version = "0.8.2", optional = true }
ab_glyph_rasterizer = { version = "0.1.3", optional = true }
# audio
cpal = { version = "0.11.0", optional = true }
minimp3 = { version = "0.5.0", optional = true }