[package]
name = "cat_audio"
version = "0.0.2"
authors = ["Clomance <Hisoskar@gmail.com>"]
edition = "2018"
homepage = "https://github.com/Clomance/CatEngine/tree/master/cat_audio"
repository = "https://github.com/Clomance/CatEngine/tree/master/cat_audio"
description = "A multichannel audio engine for CatEngine"
documentation = "https://docs.rs/cat_audio/"
license = "MIT"
readme = "README.md"
keywords = ["audio","playback"]
exclude = [
    "logo_400x400.png",
    "examples",
]

[features]
extended = []
raw = ["extended"]
# audio_post_processing = []

[package.metadata.docs.rs]
features = ["extended"]

[dependencies]
cpal = "0.11.0"
minimp3 = "0.5.0"