mod mono_windowing;
#[cfg(target_os="windows")]
pub use mono_windowing::windows::{
    App,
    AppAttributes,
    Window,
    AppControl,
    CursorIcon,
    Background,
    Fullscreen,
    Monitor,
    WindowAttributes,
    WindowClassAttributes,
    WindowInner,
    ProcessEvent,
    WindowEvent,
    VirtualKeyCode,
    EventLoopAttributes,
    OpenGLRenderContextAttributes,
    EventInterval,
    WinError,
    WindowProcedure,
    EmptyHandler,
    quit,
};