[package]
name = "cat_engine_basement"
version = "0.0.0-alpha"
authors = ["Clomance <Hisoskar@gmail.com>"]
edition = "2018"

[features]
# Event loop

own_event_handler = [] ### to set your own handler from the very start

# Window events
file_drop = []

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3.9"
features = [
    "winuser",
    "windef",
    "minwindef",
    "wingdi",
    "libloaderapi",
    "errhandlingapi",
    "processthreadsapi",
    "profileapi",
    "commctrl",
]
# optional = true


[dependencies]
image = "0.23.13"
gl = "0.14.0"