[package]
name = "cat_engine_basement"
version = "0.0.0-alpha6"
authors = ["Clomance <Hisoskar@gmail.com>"]
edition = "2021"

homepage = "https://github.com/Clomance/CatEngine"
repository = "https://github.com/Clomance/CatEngine"
description = "The CatEnigne's basement"
documentation = "https://docs.rs/cat_engine_basement/"
license = "MIT"
readme = "README.md"
keywords = ["graphics","opengl","windows","windowing"]
exclude = [
    "logo.png",
    "logo_400x400.png",
    "examples",
]

[features]
default = [
    "opengl",
    "support",
    "windowing",
    # Windows
    "wnd_proc_catch_panic",
]
support = []
opengl = ["image"]
windowing = ["image","winapi"]

# Windows
set_cursor_event = []
wnd_proc_catch_panic = []

[package.metadata.docs.rs]
features = [
    "default",
    "set_cursor_event",
]
default-target = "x86_64-pc-windows-msvc"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3.9"
features = [
    "winuser",
    "windef",
    "minwindef",
    "wingdi",
    "libloaderapi",
    "errhandlingapi",
    "profileapi",
    "winbase",
]
optional = true

[dependencies]
image = { version="0.23.13", optional = true}